### ISSUE TITLE
Improve display of reviews

### ISSUE THREAD

**Issue by tlylt** [kishore-a00/FoodIsGood-Orbital2022#16]
At the moment, the positioning of the "Vote! X" and the review itself makes it confusing to know whether the vote is for the review above it or below it. This is a case of not using space appropriately to separate items. Either considering add more space between individual reviews and its voting button, or have a outline to wrap one review + one voting button.

Besides that, the "Vote! X" is slightly too simplistic, making it unclear what for example, "Vote! 7" means... Does it mean that pressing it will vote 7 times? Best to make it clear about the number of votes, and the button to upvote. They need not be inside the same button and you do have quite a bit of space to have more info displayed.

Lastly, might want to re-consider the choice of colors. Black on Green is not exactly that common and easy on eyes. And the use of red for the button is slightly too serious. Typically red is reserved for errors and cautious stuff. I think in this screen, the voting button should be of a more neutral and inviting color instead.

![image](https://user-images.githubusercontent.com/41845017/177005593-718c728c-357c-4d64-a014-835436b98d14.png)

**Comment by tlylt** [comment]
For choice of colors, may want to consider using something like https://coolors.co/ to explore some good combinations

**Comment by kishore-a00** [comment]
Reviews and the function buttons are now side by side so that it is a cleaner interface.
Replaced colours of vote and review buttons (hopefully it looks better).
Vote button has been replaced with a "thumbs up" button with the number of likes beside it.
