### ISSUE TITLE
Add more notification of the system state

### ISSUE THREAD

**Issue by tlylt** [kishore-a00/FoodIsGood-Orbital2022#21]
When there is a state change, I am not sure if existing implementations have included notifications or ways to inform users about the state change? For example, may need to have some error handling to inform user of an incorrect operation. Or even informing users about a successful operation. This is to make the system's state more obvious and clear to the user as to what is happening after they click/press/type in something

**Comment by kishore-a00** [comment]
Added more alerts in the code to notify users accordingly.
Eg. If a user tries to submit a review with less than 3 characters, an alert pops up notifying the user that the review has to be longer.
Also, after successfully updating username, review and edit review functionalities, there will be a pop up notifying the user accordingly.
Warning alerts also pop up before a user deletes a review or signs out.
